### DISCUSSION TITLE
How can i use condition with array?

### DISCUSSION THREAD

**Discussion by zjm54321** [cargo-generate/cargo-generate#1487] [Q&A] [answered]
how can i use condition with the new placeholder "array"? I'v tried rahi grammar ,but it seems doesn't work.Is there a way to use conditional but not scripts?
This is my toml
```toml
[template]
cargo_generate_version = ">=0.23.0"

[placeholders]
peripherals = { prompt = "example", type = "array", choices = [
    "ssd1306",
    "ssd1309",
], default = [
    "ssd1306",
] }

[conditional.'"ssd1306" !in peripherals']
ignore = ["src/pac/ssd1306.rs"]

```
