### DISCUSSION TITLE
How do the `--lib` and `--bin` flags work?

### DISCUSSION THREAD

**Discussion by mscofield0** [cargo-generate/cargo-generate#362] [Q&A] [answered]
Binary projects have a `main.rs` and library ones have `lib.rs`. Which ones do I make so that cargo-generate generates the right thing?

**Comment by sassman** [comment, marked as answer]
There is [this example in the README](https://github.com/cargo-generate/cargo-generate#example-for---bin-and---lib)

```toml
[package]
# the usual stuff

[dependencies]
{% if crate_type == "bin" %}
structopt = "0.3.21"
{% endif %}
# other general dependencies

{% if crate_type == "bin" %}
[[bin]]
path = "src/main.rs"
name = "{{crate_name}}-cli"
{% endif %}
```

that illustrates the behaviour. 

So as a template author you can provide both files, and offer both capabilities. 
A user must then delete the not needed file after generating the project.
