### ISSUE TITLE
Wish:  Document  how to test with modified `libgit2`

### ISSUE THREAD

**Issue by stappersg** [cargo-generate/cargo-generate#1006]
Hi,

Here the person that encountered issue #988  (and suspects that #1005 is also involved).

My wish is that `cargo-generate` has documented
how to test with a local modified source of `libgit2`.

In `Cargo.toml` is no reference to "libgit".
If there was, it would be starting point for changing into something local.

File `Cargo.lock` has several references to `git2`.
But `Cargo.lock` is a generated file, I don't know if would make sense to modify it.

Regards  Stappers

**Comment by stappersg** [comment]
There is a _thing_ as `git-fetch-with-cli = true`.

Learnt that from https://github.com/cargo-generate/cargo-generate/issues/817#issuecomment-1483550127  it might solve #664 (Hi @tiann (reporter of #664)).

**Comment by sassman** [comment]
if you look at the `Cargo.toml` you'll find the following:

```toml
[features]
default = ["vendored-libgit2"]
vendored-libgit2 = ["git2/vendored-libgit2"]
```

As you can see `libgit2` is a dependency, or more precisely it's a feature called `vendored-libgit2` of `git2`.

**Comment by sassman** [comment]
> There is a thing as git-fetch-with-cli = true.

Yes, you can force cargo (thus also cargo-generate) into using the git cli for fetch.
It's documented here: https://doc.rust-lang.org/cargo/reference/config.html#configuration-format

```toml
[net]
retry = 3                   # network retries
git-fetch-with-cli = true   # use the `git` executable for git operations
offline = true              # do not access the network
```
