### ISSUE TITLE
feat: support multiline custom placeholders

### ISSUE THREAD

**Issue by mirsella** [cargo-generate/cargo-generate#1074]
Hello !

It would be very useful to have the option to enter multi line input with custom placeholder, like copying and pasting a block which have multiple line.
Maybe something like this:
```toml
[placeholders.input]
type = "string"
multiline = true # optional, false by default
prompt = "main puzzle input"
regex = "[^ ]"
```
And then pasting this text, for example
```
1 2
3 4
````
Would work and set the two line in input instead of setting only `1 2` and `3 4` going to the next placeholder.

Thanks !
