### ISSUE TITLE
CI speed - enable concurrency options

### ISSUE THREAD

**Issue by joshka** [cargo-generate/cargo-generate#1224]
When someone updates a PR, the running CI jobs don't really need to continue. They can often be cancelled automatically. To do this add something like the following to the various CI jobs:

```yaml
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
```
