### ISSUE TITLE
Feature request: allow multi select 

### ISSUE THREAD

**Issue by savente93** [cargo-generate/cargo-generate#1338]
I'm working on some template for myself, and I often have to work with different serde formats. What I would like is for there to be a multi select function. As an example in the `cargo-generate.toml` I'd imagine this something like: 

```toml
[placeholders.serde_formats]
type = "array"
prompt = "Which formats would you like?"
choices = ["JSON", "YAML", "CBOR", "TOML"] 
```
which I would then produce a prompt like:

```
🤷 Which formats would you like?
    [x] JSON
    [x] YAML
>   [ ]  CBOR
    [ ]  TOML
```

I'd want this to then produce an array containing the selected elements so that in the `Cargo.toml` on the template side I could do something like:

```toml
{% if "YAML" in serde_formats %}
serde_yaml = "0.9"
{% endif %}
{% if "JSON" in serde_formats %}
serde_json = "1.0.108"
{% endif %}
{% if "TOML" in serde_formats %}
toml_edit = "0.22.22"
{% endif %}
{% if "CBOR" in serde_formats %}
ciborium = "0.2.2"
{% endif %}
``` 

This is just an illustrative example, I don't actually care exactly what the formats or names turn out to be. Given what's already there, this seems like a doable feature, and if it's something the project is interested in I'd be open to making a PR for it.
