### ISSUE TITLE
Generating templates from git favorite doesn't remove `.liquid` suffixes before post hooks run

### ISSUE THREAD

**Issue by CobaltCause** [cargo-generate/cargo-generate#1375]
When generating a template from a git favorite, the contents of files ending in `.liquid` are templated correctly, but the suffix is not automatically removed before `system::command` calls in a post hook are run.

This appears to be a regression in 0.22.1 and is not present in 0.22.0.

To reproduce:

1. Add this favorite
   ```toml
   [favorites.nix]
   git = "https://gitlab.computer.surgery/charles/nix-rust-quickstart"
   branch = "main"
   ```
2. Run `cargo generate nix --name foo` and follow the prompts UNTIL it asks you to start running commands, then don't select any option
3. Inspect the contents of `/tmp/cargo-generate[...]/nix`
4. Note that files `flake.nix.liquid` and `default.nix.liquid` exist in that directory, but they should have their `.liquid` suffix removed
5. If you try allowing the first command to run, it will fail because those suffixes weren't removed

Weirdly, I can't reproduce if I instead run `cargo generate --path /path/to/exact/same/template --name foo`.
