### ISSUE TITLE
template expansion failing

### ISSUE THREAD

**Issue by Nejat** [cargo-generate/cargo-generate#1387]
**Bug Description**
While I was converting [`bevy_game_template`](https://github.com/NiklasEi/bevy_game_template) into a `cargo-generate` template, I found template expansions intended for other systems can not be mixed with`Liquid` placeholders. Specifically, in this case, the GitHub Workflows in the same project, have incompatible placeholders that conflict with `Liquid` placeholder expansion.

- valid `Liquid` placeholders do not expand, _see example_, `cargo generate ...` fails quietly
- replacing all `${{ * }}`, in the _example_, with `<< * >>` allows the liquid placeholders to expand as expected, but breaks the file's original purpose
- the issue is not the `$` but unsupported placeholder content that, I suspect, contains invalid characters like [`.`, `(`, `)`,  `=`, `'`, etc.] 
- see the  lines 18 & 20 for failing placeholder definitions

**Example**

[Original File](https://github.com/NiklasEi/bevy_game_template/blob/main/.github/workflows/release-android-google-play.yaml)

```yaml
# For setup instructions regarding this workflow, see https://www.nikl.me/blog/2023/github_workflow_to_publish_android_app/

name: release-android-google-play

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'GitHub Release'
        required: true
        type: string
      play_release:
        description: 'Release name from google play console'
        required: true
        type: string

env:
  # used for uploading the app to a GitHub release
  GAME_EXECUTABLE_NAME: {{ crate_name }} # does not expand
  BUNDLE_PATH: "target/x/release/android/mobile.aab"
  PACKAGE_NAME: "{{ package-name }}" # does not expand
  # release track; you can promote a build to "higher" tracks in the play console or publish to a different track directly
  # see track at https://github.com/r0adkll/upload-google-play#inputs for more options
  TRACK: internal
  MOBILE_DIRECTORY: mobile

permissions:
  contents: write

jobs:
  bundle-sign-release:
    runs-on: ubuntu-latest
    timeout-minutes: 40
    steps:
      - name: Install Dependencies
        run: sudo apt-get update; sudo apt-get install pkg-config libx11-dev libasound2-dev libudev-dev lld llvm
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Add Android targets
        run: rustup target add aarch64-linux-android armv7-linux-androideabi
      - name: Install cargo-binstall
        run: curl -L --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/cargo-bins/cargo-binstall/main/install-from-binstall-release.sh | bash
      - name: Install xbuild
        run: cargo binstall --git https://github.com/NiklasEi/xbuild --bin-dir x xbuild -y
      - name: Build app bundle
        run: |
          cd ${{ env.MOBILE_DIRECTORY }}
          x doctor
          x build --release --platform android --store play
      - name: sign app bundle
        run: |
          KEYSTORE_PATH=${{ runner.temp }}/upload-keystore.jks
          echo -n "${{ secrets.PLAYSTORE_KEYSTORE }}" | base64 --decode > $KEYSTORE_PATH
          jarsigner -verbose -sigalg SHA256withRSA -digestalg SHA-256 -keystore $KEYSTORE_PATH -storepass "${{ secrets.PLAYSTORE_KEYSTORE_PASSWORD }}" ${{ env.BUNDLE_PATH }} upload
      - name: Upload self-signed bundle to GitHub
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ env.BUNDLE_PATH }}
          asset_name: ${{ env.GAME_EXECUTABLE_NAME }}_${{ inputs.version }}_android.aab
          release_name: ${{ inputs.version }}
          tag: ${{ inputs.version }}
          overwrite: true
      - name: prepare Google play store secrets
        run: |
          SERVICE_ACCOUNT=${{ runner.temp }}/service-account.json
          echo -n "${{ secrets.PLAYSTORE_SERVICE_ACCOUNT }}" | base64 --decode > $SERVICE_ACCOUNT
      - name: upload bundle to Google play store
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJson: ${{ runner.temp }}/service-account.json
          packageName: ${{ env.PACKAGE_NAME }}
          releaseName: ${{ inputs.play_release }}
          releaseFiles: ${{ env.BUNDLE_PATH }}
          track: ${{ env.TRACK }}
```

**make sure you**
- [x] I'm on the latest rust version `rustup update`
- [x] I'm on the latest cargo-generate version `cargo install cargo-generate`
- [ ] In case you have an own `.gitconfig`, provide all sections that contains one of: `insteadOf`, `url`

**To Reproduce**
1. `cargo generate --path bevy_game_template --allow-commands --name my-game`
2. Generated output did not contain any expanded values, original placeholders were unchanged.
3. No errors were reported
 
**Expected behavior**
I expected the placeholders in the **_Example_** above, to expand or at least report some kind of error.

**Desktop :**
 - OS: MacOS Sequoia 
 - Version: 15.3.1
 - Build tools: gcc
 - Shell: zsh
 - `rustc --version`: rustc 1.84.1 (e71f9a9a9 2025-01-27)
 - `cargo generate --version`: cargo generate-generate 0.22.1

**Additional context**

To get past this limitation, I attempted to run a manual "expansion" with `system::command` to issue the appropriate `sed` commands, but `system::command` does not run in the temporary working folder, _see, other filed issue [can't run `system::command` that interacts with newly generated project #1388](https://github.com/cargo-generate/cargo-generate/issues/1388)_. I eventually wrote out a `zsh` script, which deletes itself, and printed a message to the user to run the script manually.

**Comment by sassman** [comment]
The issue you're phasing is explained and a workaround is available here:

https://github.com/cargo-generate/cargo-generate/discussions/843#discussioncomment-4618555

**Comment by sassman** [comment]
@Nejat was this any helpful?

**Comment by Nejat** [comment]
> [@Nejat](https://github.com/Nejat) was this any helpful?

Hi @sassman, thanks for pointing this workaround out.

It worked!

I used the following shell command to convert breaking changes to the liquid template workaround, if you want to include this in any documentation mentioning this fix.

The follow command converts all github expansions to use the workaround to "fix" the related files.

`gsed -i 's/\${{\([^\}]\+\)\}\}/${{"\1" | prepend: "{{" | append: "}}"}}/g' .github/workflows/*.yaml`

_obviously you should substitute with the files you want to change._

You can run this command in your template or keep the template files intact and run it in a `pre-hook` script, which is what I intend to do.

**Original File** 

```yaml
name: release-flow

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+*"
  workflow_dispatch:
    inputs:
      version:
        description: 'Version - in the form of v1.2.3'
        required: true
        type: string

env:
  # This variable is used to name release output files.
  GAME_EXECUTABLE_NAME: {{ crate_name }}
  GAME_OSX_APP_NAME: {{ project-app-name }}

permissions:
  contents: write

jobs:
  get-version:
    runs-on: ubuntu-latest
    steps:
      - name: Get tag
        id: tag
        run: echo "tag=${GITHUB_REF#refs/tags/}" >> "$GITHUB_OUTPUT"
    outputs:
      version: ${{ inputs.version || steps.tag.outputs.tag }}

  build-macOS:
    runs-on: macos-latest
    needs: get-version
    env:
      # macOS 11.0 Big Sur is the first version to support universal binaries
      MACOSX_DEPLOYMENT_TARGET: 11.0
      VERSION: ${{needs.get-version.outputs.version}}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Remove build script
        run: |
          rm build.rs
      - name: Install rust toolchain for Apple Silicon
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          targets: aarch64-apple-darwin
      - name: Build release for Apple Silicon
        run: |
          SDKROOT=$(xcrun -sdk macosx --show-sdk-path) cargo build --profile dist --target=aarch64-apple-darwin
      - name: Install rust toolchain for Apple x86
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          targets: x86_64-apple-darwin
      - name: Build release for x86 Apple
        run: |
          SDKROOT=$(xcrun -sdk macosx --show-sdk-path) cargo build --profile dist --target=x86_64-apple-darwin
      - name: Create Universal Binary
        run: |
          lipo -create -output target/dist/${{ env.GAME_EXECUTABLE_NAME }} target/aarch64-apple-darwin/dist/${{ env.GAME_EXECUTABLE_NAME }} target/x86_64-apple-darwin/dist/${{ env.GAME_EXECUTABLE_NAME }}
      - name: Create release
        run: |
          mkdir -p build/macos/src/Game.app/Contents/MacOS/assets
          cp -r assets/ build/macos/src/Game.app/Contents/MacOS/assets
          cp -r credits/ build/macos/src/Game.app/Contents/MacOS/credits
          cp target/dist/${{ env.GAME_EXECUTABLE_NAME }} build/macos/src/Game.app/Contents/MacOS/
          mv build/macos/src/Game.app build/macos/src/${{ env.GAME_OSX_APP_NAME }}.app
          ln -s /Applications build/macos/src/
          hdiutil create -fs HFS+ -volname "${{ env.GAME_OSX_APP_NAME }}" -srcfolder build/macos/src ${{ env.GAME_EXECUTABLE_NAME }}.dmg
      - name: Upload release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ env.GAME_EXECUTABLE_NAME }}.dmg
          asset_name: ${{ env.GAME_EXECUTABLE_NAME }}_${{ env.VERSION }}_macOS.dmg
          release_name: ${{ env.VERSION }}
          tag: ${{ env.VERSION }}
          overwrite: true

  build-linux:
    runs-on: ubuntu-latest
    needs: get-version
    env:
      VERSION: ${{needs.get-version.outputs.version}}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
      - name: Install Dependencies
        run: sudo apt-get update; sudo apt-get install pkg-config libx11-dev libasound2-dev libudev-dev
      - name: Build release
        run: |
          cargo build --profile dist
      - name: Prepare release
        run: |
          chmod +x target/dist/${{ env.GAME_EXECUTABLE_NAME }}
          mv target/dist/${{ env.GAME_EXECUTABLE_NAME }} .
      - name: Bundle release
        run: |
          tar -czf ${{ env.GAME_EXECUTABLE_NAME }}_linux.tar.gz ${{ env.GAME_EXECUTABLE_NAME }} assets credits
      - name: Upload release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ env.GAME_EXECUTABLE_NAME }}_linux.tar.gz
          asset_name: ${{ env.GAME_EXECUTABLE_NAME }}_${{ env.VERSION }}_linux.tar.gz
          release_name: ${{ env.VERSION }}
          tag: ${{ env.VERSION }}
          overwrite: true

  build-windows:
    runs-on: windows-latest
    needs: get-version
    env:
      VERSION: ${{needs.get-version.outputs.version}}
      BUILD_INSTALLER: ${{ false }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
      - name: Install dotnet
        if: ${{ env.BUILD_INSTALLER }}
        uses: actions/setup-dotnet@v3
        with:
          global-json-file: build/windows/installer/global.json
      - name: Build release
        run: |
          cargo build --profile dist
      - name: Prepare release
        run: |
          mkdir target/dist/assets && cp -r assets target/dist/assets
          mkdir target/dist/credits && cp -r credits target/dist/credits
      - name: Zip release
        uses: vimtor/action-zip@v1.1
        with:
          files: target/dist/assets/ target/dist/credits/ target/dist/${{ env.GAME_EXECUTABLE_NAME }}.exe
          dest: ${{ env.GAME_EXECUTABLE_NAME }}_windows.zip
      - name: Create Installer
        if: ${{ env.BUILD_INSTALLER }}
        run: dotnet build -p:Version=${{ env.VERSION }} -c Release build/windows/installer/Installer.wixproj --output installer
      - name: Upload release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ env.GAME_EXECUTABLE_NAME }}_windows.zip
          asset_name: ${{ env.GAME_EXECUTABLE_NAME }}_${{ env.VERSION }}_windows.zip
          tag: ${{ env.VERSION }}
          overwrite: true
      - name: Upload installer
        if: ${{ env.BUILD_INSTALLER }}
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: installer/en-US/installer.msi
          asset_name: ${{ env.GAME_EXECUTABLE_NAME }}_${{ env.VERSION }}_windows.msi
          release_name: ${{ env.VERSION }}
          tag: ${{ env.VERSION }}
          overwrite: true

  build-web:
    runs-on: ubuntu-latest
    needs: get-version
    env:
      VERSION: ${{needs.get-version.outputs.version}}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
      - name: Install Dependencies
        run: sudo apt-get update; sudo apt-get install pkg-config libx11-dev libasound2-dev libudev-dev
      - name: Install trunk
        uses: jetli/trunk-action@v0.4.0
        with:
          version: latest
      - name: Add wasm target
        run: |
          rustup target add wasm32-unknown-unknown
      - name: Build Release
        run: |
          trunk build --release
      - name: Optimize Wasm
        uses: JohannesDeml/binaryen-wasm-opt@v1
        with:
          file: dist/*.wasm
          optimize_all: true
      - name: Zip release
        uses: vimtor/action-zip@v1.1
        with:
          files: dist/
          dest: ${{ env.GAME_EXECUTABLE_NAME }}_web.zip
      - name: Upload release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ env.GAME_EXECUTABLE_NAME }}_web.zip
          asset_name: ${{ env.GAME_EXECUTABLE_NAME }}_${{ env.VERSION }}_web.zip
          release_name: ${{ env.VERSION }}
          tag: ${{ env.VERSION }}
          overwrite: true

  build-for-iOS:
    runs-on: macos-latest
    timeout-minutes: 30
    needs: get-version
    env:
      VERSION: ${{needs.get-version.outputs.version}}
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Add iOS targets
        run: rustup target add aarch64-apple-ios x86_64-apple-ios
      - name: Build app for iOS
        run: |
          cd mobile
          make xcodebuild-iphone-release
          mkdir Payload
          mv build/Build/Products/Release-iphoneos/*.app Payload
          zip -r ${{ env.GAME_EXECUTABLE_NAME }}.zip Payload
          mv ${{ env.GAME_EXECUTABLE_NAME }}.zip ${{ env.GAME_EXECUTABLE_NAME }}.ipa
      - name: Upload release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: mobile/${{ env.GAME_EXECUTABLE_NAME }}.ipa
          asset_name: ${{ env.GAME_EXECUTABLE_NAME }}_${{ env.VERSION }}_unsigned_ios.ipa
          release_name: ${{ env.VERSION }}
          tag: ${{ env.VERSION }}
          overwrite: true

  build-for-Android:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    needs: get-version
    env:
      VERSION: ${{needs.get-version.outputs.version}}
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Add Android targets
        # could add more targets like armv7-linux-androideabi here (then also add to cargo-apk config)
        run: rustup target add aarch64-linux-android
      - name: Install Cargo APK
        run: cargo install --force cargo-apk
      - name: Build app for Android
        # This uses a debug build, since release builds require keystore configuration
        # For AAB builds that can be pushed to the Play store, see the release-android-google-play workflow.
        run: ANDROID_NDK_ROOT=$ANDROID_NDK_LATEST_HOME cargo apk build --package mobile
      - name: Upload release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/debug/apk/${{ env.GAME_OSX_APP_NAME }}.apk
          asset_name: ${{ env.GAME_EXECUTABLE_NAME }}_${{ env.VERSION }}_android.apk
          release_name: ${{ env.VERSION }}
          tag: ${{ env.VERSION }}
          overwrite: true
```

**Modifed "Fixed" File** (_after running the above `gsed` command_)

```yaml
name: release-flow

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+*"
  workflow_dispatch:
    inputs:
      version:
        description: 'Version - in the form of v1.2.3'
        required: true
        type: string

env:
  # This variable is used to name release output files.
  GAME_EXECUTABLE_NAME: {{ crate_name }}
  GAME_OSX_APP_NAME: {{ project-app-name }}

permissions:
  contents: write

jobs:
  get-version:
    runs-on: ubuntu-latest
    steps:
      - name: Get tag
        id: tag
        run: echo "tag=${GITHUB_REF#refs/tags/}" >> "$GITHUB_OUTPUT"
    outputs:
      version: ${{ "inputs.version || steps.tag.outputs.tag" | prepend: "{{ " | append: " }}" }}

  build-macOS:
    runs-on: macos-latest
    needs: get-version
    env:
      # macOS 11.0 Big Sur is the first version to support universal binaries
      MACOSX_DEPLOYMENT_TARGET: 11.0
      VERSION: ${{"needs.get-version.outputs.version" | prepend: "{{" | append: "}}"}}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Remove build script
        run: |
          rm build.rs
      - name: Install rust toolchain for Apple Silicon
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          targets: aarch64-apple-darwin
      - name: Build release for Apple Silicon
        run: |
          SDKROOT=$(xcrun -sdk macosx --show-sdk-path) cargo build --profile dist --target=aarch64-apple-darwin
      - name: Install rust toolchain for Apple x86
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          targets: x86_64-apple-darwin
      - name: Build release for x86 Apple
        run: |
          SDKROOT=$(xcrun -sdk macosx --show-sdk-path) cargo build --profile dist --target=x86_64-apple-darwin
      - name: Create Universal Binary
        run: |
          lipo -create -output target/dist/${{ "env.GAME_EXECUTABLE_NAME" | prepend: "{{ " | append: " }}" }} target/aarch64-apple-darwin/dist/${{ "env.GAME_EXECUTABLE_NAME" | prepend: "{{ " | append: " }}" }} target/x86_64-apple-darwin/dist/${{ "env.GAME_EXECUTABLE_NAME" | prepend: "{{ " | append: " }}" }}
      - name: Create release
        run: |
          mkdir -p build/macos/src/Game.app/Contents/MacOS/assets
          cp -r assets/ build/macos/src/Game.app/Contents/MacOS/assets
          cp -r credits/ build/macos/src/Game.app/Contents/MacOS/credits
          cp target/dist/${{ "env.GAME_EXECUTABLE_NAME" | prepend: "{{ " | append: " }}" }} build/macos/src/Game.app/Contents/MacOS/
          mv build/macos/src/Game.app build/macos/src/${{ "env.GAME_OSX_APP_NAME" | prepend: "{{ " | append: " }}" }}.app
          ln -s /Applications build/macos/src/
          hdiutil create -fs HFS+ -volname "${{ "env.GAME_OSX_APP_NAME" | prepend: "{{ " | append: " }}" }}" -srcfolder build/macos/src ${{ "env.GAME_EXECUTABLE_NAME" | prepend: "{{ " | append: " }}" }}.dmg
      - name: Upload release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ "secrets.GITHUB_TOKEN" | prepend: "{{ " | append: " }}" }}
          file: ${{ "env.GAME_EXECUTABLE_NAME" | prepend: "{{ " | append: " }}" }}.dmg
          asset_name: ${{ "env.GAME_EXECUTABLE_NAME" | prepend: "{{ " | append: " }}" }}_${{ "env.VERSION" | prepend: "{{ " | append: " }}" }}_macOS.dmg
          release_name: ${{ "env.VERSION" | prepend: "{{ " | append: " }}" }}
          tag: ${{ "env.VERSION" | prepend: "{{ " | append: " }}" }}
          overwrite: true

  build-linux:
    runs-on: ubuntu-latest
    needs: get-version
    env:
      VERSION: ${{"needs.get-version.outputs.version" | prepend: "{{" | append: "}}"}}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
      - name: Install Dependencies
        run: sudo apt-get update; sudo apt-get install pkg-config libx11-dev libasound2-dev libudev-dev
      - name: Build release
        run: |
          cargo build --profile dist
      - name: Prepare release
        run: |
          chmod +x target/dist/${{ "env.GAME_EXECUTABLE_NAME" | prepend: "{{ " | append: " }}" }}
          mv target/dist/${{ "env.GAME_EXECUTABLE_NAME" | prepend: "{{ " | append: " }}" }} .
      - name: Bundle release
        run: |
          tar -czf ${{ "env.GAME_EXECUTABLE_NAME" | prepend: "{{ " | append: " }}" }}_linux.tar.gz ${{ "env.GAME_EXECUTABLE_NAME" | prepend: "{{ " | append: " }}" }} assets credits
      - name: Upload release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ "secrets.GITHUB_TOKEN" | prepend: "{{ " | append: " }}" }}
          file: ${{ "env.GAME_EXECUTABLE_NAME" | prepend: "{{ " | append: " }}" }}_linux.tar.gz
          asset_name: ${{ "env.GAME_EXECUTABLE_NAME" | prepend: "{{ " | append: " }}" }}_${{ "env.VERSION" | prepend: "{{ " | append: " }}" }}_linux.tar.gz
          release_name: ${{ "env.VERSION" | prepend: "{{ " | append: " }}" }}
          tag: ${{ "env.VERSION" | prepend: "{{ " | append: " }}" }}
          overwrite: true

  build-windows:
    runs-on: windows-latest
    needs: get-version
    env:
      VERSION: ${{"needs.get-version.outputs.version" | prepend: "{{" | append: "}}"}}
      BUILD_INSTALLER: ${{ "false" | prepend: "{{ " | append: " }}" }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
      - name: Install dotnet
        if: ${{ "env.BUILD_INSTALLER" | prepend: "{{ " | append: " }}" }}
        uses: actions/setup-dotnet@v3
        with:
          global-json-file: build/windows/installer/global.json
      - name: Build release
        run: |
          cargo build --profile dist
      - name: Prepare release
        run: |
          mkdir target/dist/assets && cp -r assets target/dist/assets
          mkdir target/dist/credits && cp -r credits target/dist/credits
      - name: Zip release
        uses: vimtor/action-zip@v1.1
        with:
          files: target/dist/assets/ target/dist/credits/ target/dist/${{ "env.GAME_EXECUTABLE_NAME" | prepend: "{{ " | append: " }}" }}.exe
          dest: ${{ "env.GAME_EXECUTABLE_NAME" | prepend: "{{ " | append: " }}" }}_windows.zip
      - name: Create Installer
        if: ${{ "env.BUILD_INSTALLER" | prepend: "{{ " | append: " }}" }}
        run: dotnet build -p:Version=${{ "env.VERSION" | prepend: "{{ " | append: " }}" }} -c Release build/windows/installer/Installer.wixproj --output installer
      - name: Upload release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ "secrets.GITHUB_TOKEN" | prepend: "{{ " | append: " }}" }}
          file: ${{ "env.GAME_EXECUTABLE_NAME" | prepend: "{{ " | append: " }}" }}_windows.zip
          asset_name: ${{ "env.GAME_EXECUTABLE_NAME" | prepend: "{{ " | append: " }}" }}_${{ "env.VERSION" | prepend: "{{ " | append: " }}" }}_windows.zip
          tag: ${{ "env.VERSION" | prepend: "{{ " | append: " }}" }}
          overwrite: true
      - name: Upload installer
        if: ${{ "env.BUILD_INSTALLER" | prepend: "{{ " | append: " }}" }}
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ "secrets.GITHUB_TOKEN" | prepend: "{{ " | append: " }}" }}
          file: installer/en-US/installer.msi
          asset_name: ${{ "env.GAME_EXECUTABLE_NAME" | prepend: "{{ " | append: " }}" }}_${{ "env.VERSION" | prepend: "{{ " | append: " }}" }}_windows.msi
          release_name: ${{ "env.VERSION" | prepend: "{{ " | append: " }}" }}
          tag: ${{ "env.VERSION" | prepend: "{{ " | append: " }}" }}
          overwrite: true

  build-web:
    runs-on: ubuntu-latest
    needs: get-version
    env:
      VERSION: ${{"needs.get-version.outputs.version" | prepend: "{{" | append: "}}"}}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
      - name: Install Dependencies
        run: sudo apt-get update; sudo apt-get install pkg-config libx11-dev libasound2-dev libudev-dev
      - name: Install trunk
        uses: jetli/trunk-action@v0.4.0
        with:
          version: latest
      - name: Add wasm target
        run: |
          rustup target add wasm32-unknown-unknown
      - name: Build Release
        run: |
          trunk build --release
      - name: Optimize Wasm
        uses: JohannesDeml/binaryen-wasm-opt@v1
        with:
          file: dist/*.wasm
          optimize_all: true
      - name: Zip release
        uses: vimtor/action-zip@v1.1
        with:
          files: dist/
          dest: ${{ "env.GAME_EXECUTABLE_NAME" | prepend: "{{ " | append: " }}" }}_web.zip
      - name: Upload release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ "secrets.GITHUB_TOKEN" | prepend: "{{ " | append: " }}" }}
          file: ${{ "env.GAME_EXECUTABLE_NAME" | prepend: "{{ " | append: " }}" }}_web.zip
          asset_name: ${{ "env.GAME_EXECUTABLE_NAME" | prepend: "{{ " | append: " }}" }}_${{ "env.VERSION" | prepend: "{{ " | append: " }}" }}_web.zip
          release_name: ${{ "env.VERSION" | prepend: "{{ " | append: " }}" }}
          tag: ${{ "env.VERSION" | prepend: "{{ " | append: " }}" }}
          overwrite: true

  build-for-iOS:
    runs-on: macos-latest
    timeout-minutes: 30
    needs: get-version
    env:
      VERSION: ${{"needs.get-version.outputs.version" | prepend: "{{" | append: "}}"}}
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Add iOS targets
        run: rustup target add aarch64-apple-ios x86_64-apple-ios
      - name: Build app for iOS
        run: |
          cd mobile
          make xcodebuild-iphone-release
          mkdir Payload
          mv build/Build/Products/Release-iphoneos/*.app Payload
          zip -r ${{ "env.GAME_EXECUTABLE_NAME" | prepend: "{{ " | append: " }}" }}.zip Payload
          mv ${{ "env.GAME_EXECUTABLE_NAME" | prepend: "{{ " | append: " }}" }}.zip ${{ "env.GAME_EXECUTABLE_NAME" | prepend: "{{ " | append: " }}" }}.ipa
      - name: Upload release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ "secrets.GITHUB_TOKEN" | prepend: "{{ " | append: " }}" }}
          file: mobile/${{ "env.GAME_EXECUTABLE_NAME" | prepend: "{{ " | append: " }}" }}.ipa
          asset_name: ${{ "env.GAME_EXECUTABLE_NAME" | prepend: "{{ " | append: " }}" }}_${{ "env.VERSION" | prepend: "{{ " | append: " }}" }}_unsigned_ios.ipa
          release_name: ${{ "env.VERSION" | prepend: "{{ " | append: " }}" }}
          tag: ${{ "env.VERSION" | prepend: "{{ " | append: " }}" }}
          overwrite: true

  build-for-Android:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    needs: get-version
    env:
      VERSION: ${{"needs.get-version.outputs.version" | prepend: "{{" | append: "}}"}}
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Add Android targets
        # could add more targets like armv7-linux-androideabi here (then also add to cargo-apk config)
        run: rustup target add aarch64-linux-android
      - name: Install Cargo APK
        run: cargo install --force cargo-apk
      - name: Build app for Android
        # This uses a debug build, since release builds require keystore configuration
        # For AAB builds that can be pushed to the Play store, see the release-android-google-play workflow.
        run: ANDROID_NDK_ROOT=$ANDROID_NDK_LATEST_HOME cargo apk build --package mobile
      - name: Upload release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ "secrets.GITHUB_TOKEN" | prepend: "{{ " | append: " }}" }}
          file: target/debug/apk/${{ "env.GAME_OSX_APP_NAME" | prepend: "{{ " | append: " }}" }}.apk
          asset_name: ${{ "env.GAME_EXECUTABLE_NAME" | prepend: "{{ " | append: " }}" }}_${{ "env.VERSION" | prepend: "{{ " | append: " }}" }}_android.apk
          release_name: ${{ "env.VERSION" | prepend: "{{ " | append: " }}" }}
          tag: ${{ "env.VERSION" | prepend: "{{ " | append: " }}" }}
          overwrite: true
```
