### ISSUE TITLE
Array choice not working

### ISSUE THREAD

**Issue by TheChilliPL** [cargo-generate/cargo-generate#1417]
**Describe the bug**
Array choices not working. Even using the one from the example in this repo:
```toml
[conditional.'ask_for_options'.placeholders.multi_choice]
type = "array"
prompt = "Please select one or more..."
choices = ["A", "B", "C", "D"]
default = ["B", "C"]
```
gives an error:
```
Error: invalid type for variable `multi_choice`: `array` possible values are `bool`, `string`, `text` and `editor`
```

**make sure you**
- [x] I'm on the latest rust version `rustup update`
- [x] I'm on the latest cargo-generate version `cargo install cargo-generate`
- [x] In case you have an own `.gitconfig`, provide all sections that contains one of: `insteadOf`, `url`

**To Reproduce**
1. `cargo generate <path to folder with cargo-generate.toml>`

**Expected behavior**
It should show a selection with multiple options.

**Screenshots**
![Image](https://github.com/user-attachments/assets/a317d02b-12a1-4fee-babc-8c0d596fc6d1)

**Desktop (please complete the following information):**
 - OS: [e.g. MacOS | Linux | Windows] Windows
 - Version: [e.g. 22] 11 24H2 build 26120.2992
 - Build tools: [e.g. msvc | gnu | gcc] MSVC
 - Shell: [e.g. powerShell | zsh | bash] RustRover PowerShell
 - `rustc --version`: rustc 1.85.0 (4d91de4e4 2025-02-17)
 - `cargo generate --version`: 1.22.0

**Additional context**

-
