### ISSUE TITLE
Conditionals for empty arrays?

### ISSUE THREAD

**Issue by taladar** [cargo-generate/cargo-generate#1429]
I am not sure if this is already supported in some way but I couldn't find a way to make it work but it would be useful if it was possible to ignore additional files if an array placeholder is empty (e.g. in my case a script to push deploy branches for various platforms but I select 0 platforms for that placeholder).

If this is already supported it would be nice if it was documented somewhere or part of one of the included examples since it is not obvious which syntax the conditional expressions actually use (that in itself should probably be documented somewhere too).

**Comment by sassman** [comment]
maybe you can share the things you've tried and how this example looks like?

**Comment by taladar** [comment]
Mostly I tried the obvious variants like `== []` or `is_empty()` as expressions but none of those seemed to have the desired result. Since there is no documentation on the language for the conditional expressions and other languages use a myriad of ways to express emptiness I thought it would be best to just ask what language is actually used for this.

**Comment by sassman** [comment]
The docs states the following:

![Image](https://github.com/user-attachments/assets/55be8207-c99d-45ad-ad74-50bbdc77f3e0)
[see the docs..](https://shopify.github.io/liquid/basics/types/#array)

However, I tried it on the `example-templates/arrays/README.md.liquid` like this:

```
# in line 40

[features]
{%- if features == empty %}
# we have empty features
{%- else %}
# we have features
{%- endif -%}
```

Then not selecting any features, and the rendered version looks like this:

```
[features]
# we have features
default = [""]
serde = ["serde_json"]
async = ["tokio"]
```

That means, even when not selecting anything, we end up with an array containing an empty string as it seems. 

I would consider that a bug, and create a dedicated bug issue for it.

**Comment by taladar** [comment]
Oh, I was not talking about the conditionals in templates, I was talking about the conditionals in the TOML config file that allow me to e.g. conditionally add files to an ignore list. The templates are documented.

**Comment by sassman** [comment]
It may sounds trivial, but can you please provide a example to avoid misunderstandings?

**Comment by taladar** [comment]
Basically in cargo-generate.toml I have something like

```
[template]
cargo_generate_version = ">=0.23.0"
[conditional.'publish == false']
ignore = [".github", ".github/workflows", ".github/workflows/github-release.yaml"]

[placeholders.publish]
type = "bool"
prompt = "Do you plan to publish this crate to crates.io?"
```
with a bool placeholder which works and want something similar for an array placeholder if it is empty (and I am trying to find the correct syntax for that conditional line)

```
[template]
cargo_generate_version = ">=0.23.0"
[conditional.'jenkins-platforms.is_empty()']
ignore = ["push-deploy-branches.sh"]

[placeholders.jenkins-platforms]
type = "array"
prompt = "Which OS platforms should get deploy branches for this project?"
choices = ["buster", "bullseye", "bookworm", "centos7"]
default = ["bookworm"]
```

**Comment by sassman** [comment]
Seems right now it is not supported, because we kind have some assumptions built in. 
But I would consider this actually a bug. 

Here is an example how it is going to be working:

```toml
# cargo-generate.toml

[template]
cargo_generate_version = ">=0.23.1"

[placeholders]
description = { type = "string", prompt = "Description for the crate?" }
features = { prompt = "Include features?", choices = [
    "serde",
    "async",
], default = [
    "serde",
], type = "array" }

[conditional.'features.is_empty'.placeholders.targets]
type = "array"
prompt = "Please select a target platform"
choices = [
    "aarch64-unknown-linux-gnu",
    "x86_64-unknown-linux-gnu",
    "x86_64-pc-windows-msvc",
]
default = ["x86_64-unknown-linux-gnu"]

[conditional.'features.contains("serde")'.placeholders.serde_impls]
type = "array"
prompt = "Please select a serde impl you want to use..."
choices = ["serde_json", "serde_yaml", "serde_cbor"]
default = ["serde_json"]


[conditional.'targets.contains("x86_64-pc-windows-msvc")'.placeholders.windows_specifics]
type = "array"
prompt = "Which year did you start using windows?"
choices = ["90s", "00s", "10s", "20s"]
```
