### ISSUE TITLE
FEA: specify `template_values_file` in multiple places

### ISSUE THREAD

**Issue by taurr** [cargo-generate/cargo-generate#389]
This issue takes over from an old attempt of my own (#296), and here's the idea...

What I'd like to end up with is:

1. Be able to specify default `template_values_file` in the global `.cargo-generate.toml` file
    * Maybe specify values directly in a `[values]` section?
2. Override values with `template_values_file`, definable for each defined favorite.
    * Maybe specify values directly in a `[favorites.<name>.values]` section?
3. Override with `template_values_file` from the CLI.
    * Maybe add support for `CARGO_GENERATE_<name>` style environment variables here?
    * Maybe add `--define`|`-d` as CLI argument to specify individual values?

In my mind, this should make the "value" system more complete, in that we can specify them at several well defined layers.

Before charging ahead though, I'd like to know if there's any comments/ideas/objections?

@sassman any good comments - knowing the history of #296 which basically is a failed and less well defined attempt at this?

**Comment by sassman** [comment]
> 1. Be able to specify default template_values_file in the global .cargo-generate.toml file
>     - Maybe specify values directly in a [values] section?

Could you elaborate how this would look like?

--

> Maybe specify values directly in a [favorites.<name>.values] section?

This would open up some flexibility and is a nice idea.

--

> Maybe add `--define|-d` as CLI argument to specify individual values?

This is a very good idea! 
I would even dedicate an own PR for it. It would add lot's of flexibility to users, and is very easy to use. IIRC folks have even asked for this somewhere (cannot find the issue now).

**Comment by taurr** [comment]
Example global `.cargo-generate.toml` file for the possibilities above...

```toml
[default]
# In case values are not specified anywhere else, take 'em from here (or ask interactively)
template_values_file = "~/my_default_template_values.toml"

# Specifying default values directly in the settings file
[default.values]
network_enabled = "true"
another_value = "just a demo"

[favorites.demo]
description = "Demo template for cargo-generate"
git = "https://github.com/ashleygwilliams/wasm-pack-template"
branch = "main"
# For this favorite, override the default values with the ones defined here (relative to the template folder)
template_values_file = "demo_template_values.toml"

# overriding values, from favorites
[favorites.demo.values]
another_value = "lets change the default value here!"
new_value = "and even add a new one"
```

> NOTE: This file is already used for specifying the favorites, and may be selected using the `--config` option.

... Come to think about it, I'd like to propose that in between step 1 and 2, we could support the same syntax for specifying default values directly in the `cargo-generate.toml` stored in the template.
