### ISSUE TITLE
boolean value in template values file is being ignored.

### ISSUE THREAD

**Issue by morenol** [cargo-generate/cargo-generate#514]
If  I try to generate using this [template](https://github.com/infinyon/fluvio-smartmodule-template/) and this as template value file:

```toml
[values]
smartmodule-type = "filter"
smartmodule-params = false
```

I get the prompt to fill the boolean parameter. If I set the boolean parameter as a string (using quotes) it works fine.

```toml
[values]
smartmodule-type = "filter"
smartmodule-params = "false"
```
