### ISSUE TITLE
Placeholders breaking CI

### ISSUE THREAD

**Issue by yozhgoor** [cargo-generate/cargo-generate#599]
I want to create a template with the `{{project-name}}` placeholder but the CI fail with GitHub Actions with:
```
invalid character `{` in package name: `{{project-name}}`, the first character must be a Unicode XID start character (most letters or `_`)
```

It would be great to find another solution so we can use workflow files into the template when we want to generate them too and still using them as the CI of the template itself.

**Comment by sassman** [comment]
Sorry for the late reply @yozhgoor,

Unfortunately, I'm not 100% sure if I understand your problem correctly,
depending on that there might be 2 possible solutions:

## the first
In order to use e.g. github actions in your template repository you need to wrap the whole file content where `${{ ... }}` should not be templated in the `raw` template tag.

like e.g.:

```yml
# some random github action

{% raw %}
jobs:
  check:
    name: check
    strategy:
      fail-fast: false
      matrix:
        version: [ 'macos-latest', 'ubuntu-latest', 'windows-latest']
    runs-on: ${{ matrix.version }}
    steps:

{% endraw %}
```

Here the `${{ matrix.version }}` would not be replaced by the templating engine but just copied over as it is.

## the second
in order to run ci actions on your template repository and perform a `cargo build` you need to template it first before building it.
We have a e2e test github action that does it somehow similar:
https://github.com/cargo-generate/cargo-generate/blob/main/.github/workflows/e2e-test.yml#L23

The only thing you would then need to touch is 

```yml
      - run: cargo generate ./ --name demo
```
