### ISSUE TITLE
Rename artifacts

### ISSUE THREAD

**Issue by taqtiqa-mark** [cargo-generate/cargo-generate#604]
This seems to be the same as issue #603 , but hopefully the details make clear it isn't.

It'd be nice to be able to do this in `cargo-generate.toml`:

```toml
[placeholders.sql]
type = "bool"
prompt = "Use SQL storage?"
default = false

[conditional.'sql == true']
sql-vendor = {type = "string",prompt = "Which SQL vendor?",choices = ["MySQL", "PostgreSQL", "SQLite"],default = "SQLite",}
sql-migration = {type = "string",prompt = "Which SQL migration tool?",choices = ["Refinery", "SeaORM"],default = "Refinery"}

[conditional.'sql == false']
ignore = ["entities-mysql", "entities-postgresql", "entities-sqlite", "migrations-refinery", "migrations-seaorm"]

[conditional.'sql-migration == "Refinery"']
rename=  {"migrations-refinery" = "migrations"}

[conditional.'sql-migration == "SeaORM"']
rename=  {"migrations-seaorm" = "migrations"}

[conditional.'sql-vendor == "MySQL"']
rename=  {"entities-mysql" = "entities"}

[conditional.'sql-vendor == "PostgreSQL"']
rename=  {"entities-postgresql" = "entities"}

[conditional.'sql-vendor == "SQLite"']
rename=  {"entities-sqlite"="entities"}
```

The end result would be the user would have `entities` and `migrations` folders (or files) that have within them the relevant configuration/setup.

Again, hopefully I haven't overlooked anything?

**Comment by taqtiqa-mark** [comment]
If such functionality is within scope, and not a priority, could one of the leads point to where and how they think it should be implemented and I may be able to make an attempt if it doesn't require deep familiarity with the whole code base.

**Comment by sassman** [comment]
It might me obvious what the different new config sections mean, but I would appreciate an elaboration on the meaning and behavioral details in order to the a crisp understanding with less assumptions from my side.

**Comment by taqtiqa-mark** [comment]
The idea is to have a generically named folders/files, e.g. `entities` or `migrations`, that contain within them files/code that is specific to an implementation, in the example MySQL vs PostgreSQL vs SQLite.

So the template/folder might look like this:

```bash
|--template
   |--cargo-generate.toml
    `--folder
       `--entities-sqlite
          |--Cargo.toml
          `--src
              |--mod.rs
              `--etc.
       `--entities-postgresql
          |--Cargo.toml
          `--src
              |--mod.rs
              `--etc.
       `--entities-mysql
          |--Cargo.toml
          `--src
              |--mod.rs
              `--etc.
       `--migrations-sqlite
          |--Cargo.toml
          `--src
              |--lib.rs
              |--main.rs
              `--etc.
       `--migrations-postgresql
          |--Cargo.toml
          `--src
              |--lib.rs
              |--main.rs
              `--etc.
       `--migrations-mysql
          |--Cargo.toml
          `--src
              |--lib.rs
              |--main.rs
              `--etc.
```

Then after the `cargo generate gh:some/template folder --name mine` has completed running the user has the following on their system:

```bash
|--mine
    |--entities
    |   |--Cargo.toml
    |    `--src
    |        |--mod.rs
    |        `--etc.
     `--migrations
         |--Cargo.toml
         `--src
             |--lib.rs
             |--main.rs
             `--etc.
```

Hopefully that is the additional detail you were seeking?  Let me know if I've omitted some detail.

**Comment by taqtiqa-mark** [comment]
One question is whether it would be sufficient to provide this:

```toml
[conditional.'sql-migration == "Refinery"']
rename=  {"migrations-refinery" = "migrations"}
```

Or would one have to provide this:

```toml
[conditional.'sql-migration == "Refinery"']
rename=  {migrations-refinery = "migrations"}
ignore = [migration-seaorm]
```

Somehow, it seems to me, we'd have to settle on a convention, or add a stanza to the `cargo-generate.toml` that indicates which collection of folders/files are a set from which only one will be selected - if any are selected.

Not sure if that makes sense?

**Comment by taqtiqa-mark** [comment]
I should add, that by using `[collections]`, it should also be possible for cargo-generate authors to allow their users to select a file/folder from a collection *without renaming*, or to *select multiple files/folders* from the collection via:

```toml
[conditional.'sql-entities == "SQLlite & MySQL"']
select=  {entities-sqlite = "entities", entities-mysql = "entities"}
```

In this case the use would then have

**Comment by sassman** [comment]
I think you can get the renaming working via a rhai script, as for example provided [in the hooks docs](https://cargo-generate.github.io/cargo-generate/templates/scripting.html#prepost-scripts)

So you need to 
- provide a pre-hook like `pre-migrations.rhai` 
- that would access a variable like `sql-migration` or `sql-vendor` as in your case
- depending on the variable rename the migrations folder from e.g. `migrations-refinery` to `migrations`
- depending on the variable delete unused files / folders, from the other sql vendors or migrations
- then the normal templating afterwards would sort it out

Maybe it's worth a try.

**Comment by taqtiqa-mark** [comment]
Thanks, is that a workaround or how generate supports such functionality?

**Comment by sassman** [comment]
rhai scripts to be used in pre/post hooks is a very powerful feature. It can be used to solve such very specific use cases as you got here.

**Comment by sassman** [comment]
But if renaming is such a common case, and we find more folks interested in this issue we can think of a `rename` configuration 

Since it would affect multiple files or can occur multiple times we would need to use toml tables to get this right, for example:

```toml
# Double brackets define elements of an array of tables.
[[renames]]
# here `file` and `folder` would make sense
file = "src/main_a.rs"
to = "src/main.rs"
```

with this generally available we then could combine it with [current conditionals as documented](https://cargo-generate.github.io/cargo-generate/templates/conditional.html)

so we would get the final behavior with this:

```toml
[[conditional.'sql-migration == "Refinery"'.renames]]
file = "migrations-refinery"
to = "migrations"
```

**Comment by taqtiqa-mark** [comment]
> rhai scripts ....
Bash, Zsh, Fish, Ruby, Python, etc. etc. etc. none of them... I now have to learn a new script language :(  See #618 :)

**Comment by taqtiqa-mark** [comment]
Per this [comment](https://github.com/cargo-generate/cargo-generate/issues/618#issuecomment-1145418673) - we don't have bandwidth to help flesh out any additional functionality in this issue.

**Comment by taurr** [comment]
I know this is closed now, though @taqtiqa-mark might want to know....

In some of my own templates, what I've done is this

in `cargo-generate.toml`:
```toml
[hooks]
post = ["rename.rhai"]
```

and in `rename.rhai`:
```rhai
file::rename("old-filename", "new-filename");
```

The **beauty of Rhai** it that it is simle, looks a lot like normal rust and works on all platforms, so all kinds of weird rules can be put there.

The intention with adding the `rhai`functionality was we could add a small set of powerfull extensions (which would be ever expanding), and template authors could then use these for the out-of-norm situations.
