### ISSUE TITLE
Feature: Generic pre-post hook commands

### ISSUE THREAD

**Issue by taqtiqa-mark** [cargo-generate/cargo-generate#618]
Supporting generic pre/post hook commands would allow users to employ their existing infrastructure/scripts - rather then have to re-write everything in Rhai.

Enforced behavior would be to treat `prompt_pre` and `prompt_post` as returning false.  ***Template authors don't get to override the `type` nor the `default` setting for `prompt_pre` and `prompt_post`.***
Default  `prompt_pre` and `prompt_post` strings could be:

```toml
....
prompt_pre = "Do you agree to execute pre-setup commands for `cargo generate /what/was/given here`? (y/n)"
prompt_post = "Do you agree to execute post-setup commands for `cargo generate /what/was/given here`? (y/n)"
....
```

Example:

```toml
[hooks]
prompt_pre = "Do you agree to execute xyz's pre-setup commands? (y/n)"
prompt_post = "Do you agree to execute xyz's post-setup commands? (y/n)"
pre_commands = [["rake", "init", "&>generate-pre.log"], ["make", "config", "&>>generate-pre.log"]]
post_commands = [["redo", "all", "&>generate-post.log"], ["make", "install", "&>>generate-post.log"]]
```

**Comment by taurr** [comment]
YEAH!.... templates becomes platform dependent.... TBH I am not a big fan of this one - if I really wanted to do it, I'd just utilize #598 from the existing functionality.

... Sorry if it came out a little harsh.

**Comment by sassman** [comment]
I think something that cannot be controlled by the template author are the prompts.

```toml
[hooks]
prompt_pre = "Do you agree to execute xyz's pre-setup commands? (y/n)"
prompt_post = "Do you agree to execute xyz's post-setup commands? (y/n)"
```

for security and safety reasons those must come from cargo-generate, whenever pre/post commands are given in the configuration of a template.

Also, I would think the safest way would be to present the user before the given command is executed with the specific command that is going to be executed. So that he actually can see what is going to happen and confirms that then.

The [rust std lib](https://doc.rust-lang.org/std/process/struct.Command.html#method.args) has the command API which we could feed the args into. So that we could loop over the array of commands, and take the first entry as the command, and all following values as their arguments and prepare it accordingly.
