### ISSUE TITLE
Upgrade to 0.17.0 no longer displays string-type prompt text

### ISSUE THREAD

**Issue by zeeshanlakhani** [cargo-generate/cargo-generate#790]
**Describe the bug**
Upgrade to 0.17.0 no longer displays string-type prompt text. I may have missed something that broke/changed w/ the update?

**make sure you**
- [X] I'm on the latest rust version `rustup update`
- [X] I'm on the latest cargo-generate version `cargo install cargo-generate`

**To Reproduce**
`cargo generate -v --bin --git https://github.com/fission-codes/rust-template --branch zl/template-starter`

This outputs:

```console
✔ 🤷   Which sub-template should be expanded? · rust
: foo
🔧   Destination: /Users/zeeshanlakhani/fission/rust-template/foo ...
🔧   project-name: foo ...
🔧   Generating template ...
[default: ]:
✔ 🤷   Which rust toolchain version do you want? · stable
✔ 🤷   Set up a Nix flake? · true
:
```

String-type prompts are no longer displaying text. For example, here's a couple placeholder prompts (project-name has the same issue if not supplied via `--name`. 

```toml
[placeholders.github-name]
type = "string"
prompt = "Enter your GitHub username or org."
regex = "^[A-Za-z0-9][A-Za-z0-9-]{0,38}$"

[placeholders.github-codeowner]
type = "string"
prompt = "Who is the GitHub codeowner - GitHub user or org/team?"
```

**Expected behavior**
Going back to 0.16.0 works swell, showing:

```console
✔ 🤷   Which sub-template should be expanded? · rust
🤷   Project Name : flybynight
🔧   Destination: /Users/zeeshanlakhani/fission/rust-template/flybynight ...
🔧   Generating template ...
🤷   Who is the GitHub codeowner - GitHub user or org/team? : zeeshanlakhani
🤷   Enter a description of the project. [default: ]: description
✔ 🤷   Set up a Nix flake? · true
✔ 🤷   Which rust toolchain version do you want? · stable
🤷   Enter your GitHub username or org. :
```

**Desktop (please complete the following information):**
 - OS: MacOS
 - Version: 12.6
 - Shell: fish
 - `rustc --version`: 1.64.0
 - `cargo generate --version`: 0.17.0
