### ISSUE TITLE
Update to 0.17.* disallows empty default for string types

### ISSUE THREAD

**Issue by zeeshanlakhani** [cargo-generate/cargo-generate#793]
**Describe the bug**

Update to 0.17.* disallows empty default for string types.

**make sure you**
- [X] I'm on the latest rust version `rustup update`
- [X] I'm on the latest cargo-generate version `cargo install cargo-generate`

**To Reproduce**
`cargo generate -v --bin --git https://github.com/fission-codes/rust-template --branch zl/template-starter`

The generate toml contains:

```toml
[placeholders.description]
type = "string"
prompt = "Enter a description of the project."
default = ""
```

This outputs:

```console
🤷   Enter a description of the project.:
```

**Expected behavior**
Going back to 0.16.0 works swell, showing:

```console
🤷   Enter a description of the project. [default: ] []:
```

**Desktop (please complete the following information):**
 - OS: MacOS
 - Version: 12.6
 - Shell: fish
 - `rustc --version`: 1.64.0
 - `cargo generate --version`: 0.17.0
