### ISSUE TITLE
Incorrect behaviour with template from git vs from path

### ISSUE THREAD

**Issue by KaitlynEthylia** [cargo-generate/cargo-generate#914]
**Describe the bug**
Conditionals are interpreted differently when selecting a template from --git and --path

**make sure you**
- [X] I'm on the latest rust version `rustup update`
- [X] I'm on the latest cargo-generate version `cargo install cargo-generate`
- [X] In case you have an own `.gitconfig`, provide all sections that contains one of: `insteadOf`, `url`

My `.gitconfig` contains nothing that should cause this behaviour:
```gitconfig
[user]
	name = KaitlynEthylia
	email = kaitlyyn.ethylia@proton.me
[commit]
	gpgsign = true
[init]
	defaultBranch = mistress
[core]
	autocrlf = false
	eol = lf
```

**To Reproduce**
1. Steps to reproduce the behavior:
2. Clone my rust-template repo
3. Run cargo generate with `--path rust-template`
4. Run cargo generate with `gh:KaitlynEthylia/rust-template`
5. See that the results are different

`git clone https://github.com/KaitlynEthylia/rust-template`
`cargo generate --path rust-template/ -d test=false -d cratetype=bin -n path-test`
`cargo generate gh:KaitlynEthylia/rust-template -d test=false -d cratetype=bin -n git-test`

`ls path-test/src` Contains 1 file: `main.rs`
`ls git-test/src` Contains 2 files: `main.rs`, and `lib.rs`

**Expected behavior**
There should be no `lib.rs` in the git-test/src folder

**Screenshots**
I don't think any are necessary, but I can follow up with screenshots if requested.

**Desktop (please complete the following information):**
 - OS: Arch
 - Version: Not Applicable (Arch Rolling Release, Kernel 6.2.10)
 - Build tools: GNU
 - Shell: Zsh
 - `rustc --version`: 1.68.2
 - `cargo generate --version`: 0.18.1

**Additional context**
[A link to my template repository](https://github.com/KaitlynEthylia/rust-template)

The significant part being the cargo-generate.toml file:
```toml
# added because builtin doesn't allow for 'both' option
[placeholders.cratetype]
type = "string"
prompt = "What type of crate is this?"
choices = ["bin", "lib", "both"]
default = "bin"

[conditional.'cratetype == "lib"']
ignore = ["src/main.rs"]

[conditional.'cratetype == "bin"']
ignore = ["src/lib.rs"]

[placeholders.test]
type = "bool"
prompt = "Use default test?"
default = false

[conditional.'!test']
ignore = ["src/test.rs"]
```
