### ISSUE TITLE
RFC: Ready-made configurations/presets for templates

### ISSUE THREAD

**Issue by therealprof** [cargo-generate/cargo-generate#92]
In the embedded WG we have another challenge with templates to solve. Once we have #17, it would be nice to provide additional guidance for the user to break down sensible value combinations into presets which can be stored in the templates to vastly simplify the setup.

An example for a system like this exists in the C/C++ embedded world with [platform.io](https://platformio.org/) which (amongst other things) provides something very similar to `cargo-generate`. Instead of providing a lot of details (most will probably not even know from the top of their head) about the platform one is interested in, there're presets which can be selected, e.g.:

```
# platformio boards stm32

Platform: ststm32
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
ID                    MCU            Frequency  Flash   RAM    Name
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
1bitsy_stm32f415rgt   STM32F415RGT   168MHz    1MB     128KB  1Bitsy
b96b_f446ve           STM32F446VET6  168MHz    512KB   128KB  96Boards B96B-F446VE
armstrap_eagle1024    STM32F417VGT6  168MHz    1MB     192KB  Armstrap Eagle 1024
armstrap_eagle2048    STM32F427VIT6  168MHz    1.99MB  256KB  Armstrap Eagle 2048
...
```

Creating a new project using such a template will result in nicely configured environment which allows to jump right into development.

**Comment by therealprof** [comment]
Yes, something along the lines would be great.

**Comment by softprops** [comment]
Porteurbars has this albiet through slightly different means, it uses env vars for template input sourced from a .env file that exists in the templates source repo 
 https://github.com/softprops/porteurbars/blob/master/README.md#creating-templates

@ashleygwilliams I wouldn't might joining forces a bit on the plugin. I use porteurbars outside of rust contexts but many of my recent projects have a strong rust focus so there's motivation to bring some of porteurbars convince closer to the existing rust/cargo ecosystem.

**Comment by taurr** [comment]
2 options come to my mind here, of which only the 2'nd can solve this issue 100%

---
## Option 1

Use `conditionals` in `cargo-generate.toml`:
```toml
[template]
cargo_generate_version = ">0.8.0"

[placeholders]
flavor = { type="string", prompt="Select flavor", choices=["1bitsy_stm32f415rgt", "b96b_f446ve", "armstrap_eagle1024", "armstrap_eagle2048"] }

[conditional.'flavor=="1bitsy_stm32f415rgt"'.placeholders]
mcu = { type="string", default="STM32F415RGT", prompt="MCU?" }
frequency = { type="string", default="168MHz", prompt="Frequency?" }
flash = { type="string", default="1MB", prompt="Flash?" }
ram = { type="string", default="128KB", prompt="RAM?" }

[conditional.'flavor=="b96b_f446ve"'.placeholders]
mcu = { type="string", default="STM32F446VET6", prompt="MCU?" }
frequency = { type="string", default="168MHz", prompt="Frequency?" }
flash = { type="string", default="512KB", prompt="Flash?" }
ram = { type="string", default="128KB", prompt="RAM?" }

[conditional.'flavor=="armstrap_eagle1024"'.placeholders]
mcu = { type="string", default="STM32F417VGT6", prompt="MCU?" }
frequency = { type="string", default="168MHz", prompt="Frequency?" }
flash = { type="string", default="1MB", prompt="Flash?" }
ram = { type="string", default="192KB", prompt="RAM?" }

[conditional.'flavor=="armstrap_eagle2048"'.placeholders]
mcu = { type="string", default="STM32F427VIT6", prompt="MCU?" }
frequency = { type="string", default="168MHz", prompt="Frequency?" }
flash = { type="string", default="1.99MB", prompt="Flash?" }
ram = { type="string", default="256KB", prompt="RAM?" }
```

This one would ask for all the options, but at least with sensible defaults...

Not really that nice... it seems this solution is missing the possibility to specify values instead of just placeholders :nerd_face:

Oh... and you can't get a nice listning of the different flavors and what they contain.

---

## Option 2

Probably the best option.

Once/if #445 lands, it will be easy to create a small pre-script - this is an example that works with the current draft...

In `cargo-generate.toml`:
```toml
[hooks]
pre = ["flavor-selection.rhai"]
````

In `flavor-selection.rhai`:
```rhai
print("Platform: ststm32");
print("----------------------------------------------------------------------------------");
print("ID                    MCU            Frequency  Flash   RAM    Name");
print("----------------------------------------------------------------------------------");
print("1bitsy_stm32f415rgt   STM32F415RGT   168MHz    1MB     128KB  1Bitsy");
print("b96b_f446ve           STM32F446VET6  168MHz    512KB   128KB  96Boards B96B-F446VE");
print("armstrap_eagle1024    STM32F417VGT6  168MHz    1MB     192KB  Armstrap Eagle 1024");
print("armstrap_eagle2048    STM32F427VIT6  168MHz    1.99MB  256KB  Armstrap Eagle 2048");

let flavor = variable::get("flavor");
do {
    let selection_ok = switch flavor {
        "1bitsy_stm32f415rgt" => {
            variable::set("mcu", "STM32F415RGT");
            variable::set("frequency", "168MHz");
            variable::set("flash", "1MB");
            variable::set("ram", "128KB");
            true
        }
        "b96b_f446ve" => {
            variable::set("mcu", "STM32F446VET6");
            variable::set("frequency", "168MHz");
            variable::set("flash", "512KB");
            variable::set("ram", "128KB");
            true
        }
        "armstrap_eagle1024" => {
            variable::set("mcu", "STM32F417VGT6");
            variable::set("frequency", "168MHz");
            variable::set("flash", "1MB");
            variable::set("ram", "192KB");
            true
        }
        "armstrap_eagle2048" => {
            variable::set("mcu", "STM32F427VIT6");
            variable::set("frequency", "168MHz");
            variable::set("flash", "1.99MB");
            variable::set("ram", "256KB");
            true
        }
        _ => {
            flavor = variable::prompt(
                "Select ID",
                "1bitsy_stm32f415rgt",
                ["1bitsy_stm32f415rgt", "b96b_f446ve", "armstrap_eagle1024", "armstrap_eagle2048"]);
            false
        }
    };
} until selection_ok;
variable::set("flavor", flavor);
```

With this script, the user will see the list, and be able to select the flavor interactively. It is also possible to just specify the flavor directly using e.g. `-d flavor="b96b_f446ve"` straight from the commandline.
